### PR TITLE
Bug fix

### LINKED ISSUE #3: Found A Bug at Start Button
I have found a bug while looking at your project.

When I double click on start button, the stopwatch is not pausing and resetting.

Try disabling start button once the stopwatch is started or remove start once the stopwatch starts and display only pause button and when stopwatch is paused display only start button.

Hope this is helpful

### PR DESCRIPTION
**Pull request by vasudevarao3**
Resending the Fixed bug

### CODE REVIEW

File: script.js [hunk 1]
```diff
@@ -83,6 +83,7 @@ function writeMilliSecondToDoc(givenMilliSecondTime, writeToDiv) {
 let elapsedTime = 0;
 let hasPausedStopWatch = true;
 let timerIntervalStopWatchId = null;
+let stopwatchStarted = false;
```
Comment (iamwatchdogs) [inline script.js]: Instead of creating a new variable, Try using the existing `hasPausedStopWatch` variable.

> Remove `stopwatchStarted` and use `hasPausedStopWatch`.

File: script.js [hunk 2]
```diff
@@ -92,10 +93,12 @@ function pause(forResetOrToggle = false) {
     else if (isVisible == 'stopwatch') {
         clearInterval(timerIntervalStopWatchId);
         hasPausedStopWatch = true;
+        stopwatchStarted = false;
```
Comment (iamwatchdogs) [inline script.js]: This will not be required if you use the `hasPausedStopWatch` variable.

File: script.js [hunk 3]
```diff
@@ -106,20 +109,23 @@ function pause(forResetOrToggle = false) {
...
-    hasPausedStopWatch = false;
-    
-    // Starting time in milliseconds.
-    let startTime = Date.now() - elapsedTime;
-    
-    timerIntervalStopWatchId = setInterval(function() {
-        
-        // Calculating elapsed time in milliseconds.
-        elapsedTime = Date.now() - startTime;
+    if(stopwatchStarted == false){
```
Comment (iamwatchdogs) [inline script.js]: Instead of using the **conditionally equal-to** `==` operator, why don't you **use the logical not `!` operator** *( as you doing some **logical operation** on a boolean type variable )*?

```suggestion
    if( !stopwatchStarted ){
```

<br>

This variable will not be needed if you use the existing `hasPausedStopWatch` variable. Then the resulting logic will be...
```suggestion
    if(hasPausedStopWatch){
```

File: script.js [hunk 4]
```diff
@@ -148,6 +154,7 @@ let isTimerSet = false;
 let milliSecCountDown = 0;
 let timerIntervalCountDownTimerId = null;
 let hasPausedCountDownTimer = false;
+let countDownTimerStarted = false;
```
Comment (iamwatchdogs) [inline script.js]: As I have mentioned above, Using the existing `hasPausedCountDownTimer` variable is enough to complete your bug-fixing logic.

File: script.js [hunk 5]
```diff
@@ -92,10 +93,12 @@ function pause(forResetOrToggle = false) {
     else if (isVisible == 'stopwatch') {
         clearInterval(timerIntervalStopWatchId);
         hasPausedStopWatch = true;
+        stopwatchStarted = false;
     } 
     else if (isVisible == 'countdown') {
         clearInterval(timerIntervalCountDownTimerId);
         hasPausedCountDownTimer = true;
+        countDownTimerStarted = false;
```
Comment (iamwatchdogs) [inline script.js]: Do not forget to update this statement *( remove the statement )*, after you're done rewrite your bug-fixing logic by using the existing variable `hasPausedCountDownTimer`.

File: script.js [hunk 6]
```diff
@@ -158,14 +165,18 @@ function setCountDownTimer() {
         milliSecCountDown = min * 60000;
         writeMilliSecondToDoc(milliSecCountDown, 'cdtimer');
         isTimerSet = true;
+        countDownTimerStarted =false;
```
Comment (iamwatchdogs) [inline script.js]: Remove this statement after you're done rewriting your bug-fixing logic with the existing variable.

File: script.js [hunk 7]
```diff
@@ -158,14 +165,18 @@ function setCountDownTimer() {
...
     }
 }
 
 // Function to start the Countdown Timer.
 function startCountDownTimer() {
     if( !isTimerSet ) {
         alert('Please Set the timer !!!...');
-    } else {
+    } 
+    else if(countDownTimerStarted == false){
```
Comment (iamwatchdogs) [inline script.js]: Update this statement after you're done rewriting your bug-fixing logic with the existing variable.

No need for an additional variable like `countDownTimerStarted`, use the existing variable `hasPausedCountDownTimer`.

File: script.js [hunk 8]
```diff
@@ -158,14 +165,18 @@ function setCountDownTimer() {
...
+        countDownTimerStarted = true;
```
Comment (iamwatchdogs) [inline script.js]: Remove this statement after you have rewritten your logic with above mentioned changes

File: script.js
Comment (iamwatchdogs) [inline script.js:1]: While I was checking this file, I found a few unnecessary statements. These are the two statements that are found in `startCountDownTimer()` :

```js
function startCountDownTimer() {
  // Beginning part of the code

  hasPausedCountDownTimer = true;
  isTimerSet = false;

  // Remaining part of the code
}
```

These statements exist around line no. 181,182. Can you remove them for me?

**Review by iamwatchdogs — CHANGES_REQUESTED** [review]
Please update the `script.js` with the given changes...

**Review by iamwatchdogs — APPROVED** [review]
